FROM adoptopenjdk/openjdk11:ubi
# Building
# mvn package -f source/saldoextrato-api-v1/saldoextrato -DskipTests
# docker build -f docker/Dockerfile.saldoextrato-api.v1 -t viniciusmartinez/saldoextrato-api:1.0  --build-arg JAR_FILE="source/saldoextrato-api-v1/saldoextrato/target/saldoextrato-0.0.2-SNAPSHOT.jar" .
# Running
# docker run -it -p 8080:8080 viniciusmartinez/saldoextrato-api:2.0
ARG JAR_FILE
RUN mkdir /opt/app
COPY ${JAR_FILE} /opt/app
EXPOSE 8080
CMD ["java", "-jar", "/opt/app/saldoextrato-0.0.2-SNAPSHOT.jar"]
